### ISSUE TITLE
Forward back to Http but not Https after click on "Clear History"

### ISSUE THREAD

**Issue by PengyuTang** [clafonta/Mockey#101]
Hi,

we recently set up Mockey with https. But when we do clear history, it will forward back to http. For example, "https://xxx/history", after clear history, it forwards to "xxx/history". Is there any configuration we need do? We only find the issue on this button.

Thank you,

Roc.

**Comment by clafonta** [comment]
Roc - When you can, provide me a little more detail to recreate the issue so I can debug and fix.

**Comment by PengyuTang** [comment]
We use Docker container for Mockey, and deploy it on AWS. After hitting the domain name will go to load balance. The load balance will pick up a box to access. We close some ports, and only open 443. The domain we give is like "https://ourMockey.com", after clicking on "clear history", it redirect to "http://ourMockey.com/history". 
By the way, those services url are defined like "http://ourMockey.com:80/service/btcs/v1"

**Comment by PengyuTang** [comment]
I think the reason is here, we use load balancer with "https", but the following code will try to redirect to http.

   the code is on HistoryServlet.java
  String contextRoot = req.getContextPath();
  resp.sendRedirect(Url.getContextAwarePath("/history", contextRoot));

**Comment by clafonta** [comment]
It looks similar to this issue: https://stackoverflow.com/questions/18891210/how-to-reproduce-sendredirect-issue-https-change-to-http

..since I don't run in a load balancer, I'm unable to reproduce. Before I spend time figuring out how to address this (keeping Mockey friendly w/ both http:// and https://), can you see if a Web Server config change can fix this?

**Comment by clafonta** [comment]
I'm going to close this - I believe it's fixed.
