### ISSUE TITLE
No longer able to start Mockey with definition file (-f option missing)

### ISSUE THREAD

**Issue by joshnhickman** [clafonta/Mockey#89]
I updated to the latest version of Mockey (2.0.69) and found that the `-f|--file` option is missing. Digging through commits, it looks like it was removed in 44f9410048857dfd0a82e0b0a7202c41937cf5be (specifically [line 67 in JettyRunner](https://github.com/clafonta/Mockey/commit/44f9410048857dfd0a82e0b0a7202c41937cf5be#diff-50cca99e40a3ba2304b754170dbaef01L67)) but I don't see it mentioned in the commit message or the readme, and the help page still mentions it under initialization. Has this functionality been moved somewhere else?

**Comment by clafonta** [comment]
Josh - apologies for this. Updated the help section and RELEASENOTES.txt. 

I removed -f option from startup because I had a bigger value/need to get Mockey to work as a WAR in a Tomcat server. As a consequence, the process to handle the options and various ways to startup Mockey needed to be revisited - cause of confusion and startup failures. Since you still need this, then I'll bring it back but I need a couple of days to rework startup options, which include single-definition-file, environment variable, default location, some-other-location, etc., with consideration of deploying as a WAR or an executable JAR/jetty file.  In the meantime, you may want to look at:
https://github.com/clafonta/Mockey/wiki/Downloads
...which still supports the -f option.

**Comment by joshnhickman** [comment]
There's no rush on this, it's not blocking me on anything. I was updating some of our mocks and figured I'd upgrade for the improved UI, and I kept around an old build of the jar just in case something like this happened. Is there any other way to start up Mockey with a pre-set definition, or does it have to be done after the fact through the UI right now?

**Comment by clafonta** [comment]
Yes/no.  After you start-up Mockey for the first time and load up your definitions, then toggle Mockey to "Write-to-file" (via the UI), it will write all your settings to the file system, and be available upon restart, without any toggles needed. For more insight, see http://127.0.0.1:8080/help#storage and http://127.0.0.1:8080/help#startup.

**Comment by joshnhickman** [comment]
That should serve us well enough for now.

Just so you know, our use case for this is to allow automated deployments of Mockey. We have a script that downloads the jar and starts it up with a pre-set definition that we store in git. Having to do it through the UI when we deploy it to a new place isn't a deal breaker, but it would be much better if we could automate it all.

**Comment by clafonta** [comment]
Fix in (feature returned). Let me know of anything else you may need.
